# Generated by Django 4.2.7 on 2025-04-25 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='协议名称')),
                ('description', models.TextField(blank=True, verbose_name='协议描述')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='默认端口')),
            ],
            options={
                'verbose_name': '协议',
                'verbose_name_plural': '协议',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PacketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='捕获时间')),
                ('source_ip', models.GenericIPAddressField(verbose_name='源IP地址')),
                ('source_port', models.IntegerField(verbose_name='源端口')),
                ('destination_ip', models.GenericIPAddressField(verbose_name='目标IP地址')),
                ('destination_port', models.IntegerField(verbose_name='目标端口')),
                ('payload', models.TextField(blank=True, verbose_name='数据内容')),
                ('packet_size', models.IntegerField(default=0, verbose_name='数据包大小(字节)')),
                ('direction', models.CharField(choices=[('inbound', '入站'), ('outbound', '出站')], default='inbound', max_length=10, verbose_name='方向')),
                ('status', models.CharField(choices=[('allowed', '已允许'), ('blocked', '已阻止'), ('suspicious', '可疑')], default='allowed', max_length=10, verbose_name='状态')),
                ('protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packet_analyzer.protocol', verbose_name='协议')),
            ],
            options={
                'verbose_name': '数据包日志',
                'verbose_name_plural': '数据包日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeepInspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_protocol', models.CharField(max_length=50, verbose_name='应用层协议')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='内容类型')),
                ('detected_patterns', models.TextField(blank=True, verbose_name='检测到的模式')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=10, verbose_name='风险等级')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='是否恶意')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('packet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packet_analyzer.packetlog', verbose_name='关联数据包')),
            ],
            options={
                'verbose_name': 'DPI分析结果',
                'verbose_name_plural': 'DPI分析结果',
            },
        ),
    ]
