# Generated by Django 4.2.7 on 2023-04-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rules', '0001_initial'),
        ('packet_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetlog',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_packets', to='firewall_rules.rule', verbose_name='匹配规则'),
        ),
    ]
