# Generated by Django 4.2.7 on 2025-04-29 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packet_analyzer', '0002_auto_20250425_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='捕获时间'),
        ),
    ]
