# Generated by Django 4.2.7 on 2025-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_analyzer', '0003_alter_packetlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepinspectionresult',
            name='decoded_content',
            field=models.TextField(blank=True, null=True, verbose_name='解码内容'),
        ),
    ]
