# Generated by Django 4.2.7 on 2025-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_analyzer', '0004_deepinspectionresult_decoded_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetlog',
            name='processing_time',
            field=models.FloatField(default=0.0, verbose_name='处理时间(毫秒)'),
        ),
    ]
