# Generated by Django 4.2.7 on 2025-05-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_analyzer', '0005_packetlog_processing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetlog',
            name='attack_type',
            field=models.CharField(default='normal', max_length=50, verbose_name='攻击类型'),
        ),
        migrations.AddField(
            model_name='packetlog',
            name='raw_request',
            field=models.TextField(blank=True, null=True, verbose_name='原始请求'),
        ),
    ]
