# Generated by Django 4.2.7 on 2025-05-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packet_analyzer', '0006_packetlog_attack_type_packetlog_raw_request'),
    ]

    operations = [
    ]
