# Generated by Django 4.2.7 on 2025-05-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rules', '0002_auto_20250425_1553'),
        ('packet_analyzer', '0010_packetlog_processing_time_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetlog',
            name='attack_type',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True, verbose_name='攻击类型'),
        ),
        migrations.AlterField(
            model_name='packetlog',
            name='direction',
            field=models.CharField(choices=[('inbound', '入站'), ('outbound', '出站')], max_length=10, verbose_name='方向'),
        ),
        migrations.AlterField(
            model_name='packetlog',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firewall_rules.rule', verbose_name='匹配规则'),
        ),
        migrations.AlterField(
            model_name='packetlog',
            name='packet_size',
            field=models.IntegerField(verbose_name='包大小(字节)'),
        ),
        migrations.AlterField(
            model_name='packetlog',
            name='payload',
            field=models.TextField(blank=True, verbose_name='负载内容'),
        ),
        migrations.AlterField(
            model_name='packetlog',
            name='protocol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='packet_analyzer.protocol', verbose_name='协议'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packetlog',
            name='status',
            field=models.CharField(choices=[('allowed', '允许'), ('blocked', '阻止'), ('suspicious', '可疑'), ('error', '错误')], max_length=15, verbose_name='状态'),
        ),
    ]
