# Generated by Django 4.2.7 on 2025-04-25 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='告警时间')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=10, verbose_name='告警级别')),
                ('title', models.CharField(max_length=100, verbose_name='告警标题')),
                ('description', models.TextField(verbose_name='告警内容')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='源IP地址')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('paused', '已暂停'), ('error', '错误')], default='stopped', max_length=20, verbose_name='系统状态')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='内存使用率')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统状态',
                'verbose_name_plural': '系统状态',
            },
        ),
        migrations.CreateModel(
            name='TrafficStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='统计时间')),
                ('inbound_packets', models.BigIntegerField(default=0, verbose_name='入站数据包数')),
                ('outbound_packets', models.BigIntegerField(default=0, verbose_name='出站数据包数')),
                ('inbound_bytes', models.BigIntegerField(default=0, verbose_name='入站流量(字节)')),
                ('outbound_bytes', models.BigIntegerField(default=0, verbose_name='出站流量(字节)')),
                ('blocked_packets', models.IntegerField(default=0, verbose_name='拦截数据包数')),
            ],
            options={
                'verbose_name': '流量统计',
                'verbose_name_plural': '流量统计',
                'ordering': ['-timestamp'],
            },
        ),
    ]
