# Generated by Django 4.2.7 on 2025-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_trafficstatistics_suspicious_packets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficstatistics',
            name='suspicious_packets',
        ),
        migrations.AddField(
            model_name='trafficstatistics',
            name='inbound_bytes_per_sec',
            field=models.FloatField(default=0, verbose_name='入站流量(字节/秒)'),
        ),
        migrations.AddField(
            model_name='trafficstatistics',
            name='outbound_bytes_per_sec',
            field=models.FloatField(default=0, verbose_name='出站流量(字节/秒)'),
        ),
    ]
