# Generated by Django 4.2.7 on 2025-04-29 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_trafficstatistics_suspicious_packets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='告警时间'),
        ),
        migrations.AlterField(
            model_name='trafficstatistics',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='统计时间'),
        ),
    ]
