# Generated by Django 4.2.7 on 2023-04-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rules', '0001_initial'),
    ]

    operations = [
        # RulePattern和pattern字段已经在0001_initial.py中创建
    ]
